---
- hosts: windows
  gather_facts: False
  connection: local

  tasks:
    - name: Install Java
      win_chocolatey:
        name: "{{ jdk_package }}"
        state: present
        version: "{{ java_major_version }}.{{ java_minor_version }}"

    - name: Set Java_home
      win_environment:
        state: present
        name: JAVA_HOME
        value: 'c:\program files\java\jdk1.{{ java_major_version }}_{{ java_minor_version }}'
        level: machine

    - name: Set Java_home
      win_environment:
        state: present
        name: CATALINA_HOME
        value: 'C:\Temp\apache-tomcat-8.5.32\lib'
        level: machine

    - name: Add Java and catlina home to path
      win_path:
        elements:
          - 'c:\program files\java\jdk{{ java_major_version }}_{{ java_minor_version }}\bin'
          - 'C:\Temp\apache-tomcat-8.5.32\lib'
 
    - name: Install all security, critical, and rollup updates
      win_updates:
      category_names:
         - SecurityUpdates
         - CriticalUpdates
         - UpdateRollups     

    - name: Copy files/temp_files to c:\temp
      win_copy:
        src: ../files/
        dest: c:\Temp

    - name: Starting tomcat
      win_command:
         path: C:\Temp\apache-tomcat-8.5.32\bin\startup.bat


    - mail:
        host: smtp.gmail.com
        port: 587
        username: vallabh4@gmail.com
        password: 569383677
        to: shree.vallabh@kuliza.com
        subject: Test
        body: "Windows update in {{ ansible_host }} has successfully completed"
      run_once: True
      delegate_to: localhost
