
---
- hosts: windows
  gather_facts: False
  connection: local

  tasks:
    - name: Install notepadplusplus version 6.6
      win_chocolatey:
         name: notepadplusplus
         version: '7.5.2'
